version: '3.5'

networks:
 localdev:
  name: localdev
    external:true

services: 
  profileapi:
     image: profileapi
     build:
       context: ./Profile.Service.Api
       dockerfile: Dockerfile
     networks:
      - localdev
     ports: 
      - "0.0.0.0:5001:80"
     restart: 
      always 

  profilegateway:
    image: profilegateway
    build:
      context: ./Profile.Service.Gateway
      dockerfile: Dockerfile
    depends_on:
     - profileapi
    networks:
     - localdev
    ports: 
     - "0.0.0.0:5001:80"
    restart: 
      always

    
